version: '3'
services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/usr/src/app
  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api
  certs:
    image: nginx:alpine
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - api
      - client
    ports:
      - 443:443
    command: >
      sh -c "apk add openssl;
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/key.pem -out /etc/nginx/certs/cert.pem -subj '/CN=localhost';
      nginx -g 'daemon off;'"
