version: '3'
services:
  api:
    container_name: card-profile-go-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/backend
